#! /usr/bin/env python
# encoding: utf-8

'''
@author: Milos Subotic <milos.subotic.sm@gmail.com>
@license: MIT
'''

###############################################################################

import os
import fnmatch
import shutil
import datetime

import waflib

###############################################################################

def options(opt):
	opt.load('compiler_c')

	opt.add_option(
		'--debug',
		action = 'store_true',
		dest = 'debug',
		default = False, 
		help = 'enable compiler debug information'
	)


def configure(conf):
	conf.load('compiler_c')

	conf.env.CFLAGS += ['-std=c99']

	if conf.options.debug:
		conf.env.CFLAGS.append('-g')

def build(bld):
	bld.program(
		source = ['ppm.c', 'painter_2d.c', 'main.c'],
		target = 'algo'
	)

###############################################################################

